### ISSUE TITLE
Does it support Android?

### ISSUE THREAD

**Issue by underline9396** [mrtrizer/UnityPiper#3]
This is a very cool text-to-speech project!
I got it working on Windows, but I am struggling with Android. I suppose it is not supported, can you please confirm?

Thanks!

**Comment by mrtrizer** [comment]
Well, I think you can get it working if you build it for android, the problem is that the original lib doesn't have dll build target in the CMake and I had to add it, with it I guess you can to build it for arm v7 with android NDK and drop the library to the plugins

**Comment by adem-rguez** [comment]
hello, i am facing the same issue, i need to have the plugin for android (building for oculus) but i after sevral days i still can't use cmake to create it, have u done it?

**Comment by underline9396** [comment]
@adem-rguez I am also building for Oculus, I ended up using wit.ai from Meta. It has text-to-speech with different voices, and it also supports language understanding. It's pretty cool, but it requires internet access.

**Comment by adem-rguez** [comment]
lol, i was using wit as well, but ended up canceling that due to plugin issues and also the unability to stream audio, but for piper i managed to implement a streaming solution in unity, that's why

**Comment by adem-rguez** [comment]
@mrtrizer could you try building for android using cmake? and thank you
