### ISSUE TITLE
How do I use Speaker ID?

### ISSUE THREAD

**Issue by Graylington** [mrtrizer/UnityPiper#4]
In PiperLib.cs I can see "public OptionalLong speakerId;" but I can't find any way to use it for multi-speaker voices.

**Comment by mrtrizer** [comment]
Oh, sorry, I can't really tell you what exactly this is, it's not clear from original code how this is supposed to work, I added this just for compatibility. I guess the answers are around here
Try to look for answers in the original lib docs or sources
https://github.com/rhasspy/piper
